# Generated by Django 5.2.1 on 2025-06-03 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('post', models.CharField(choices=[('CFO', 'CFO'), ('CEO', 'CEO')], max_length=3)),
            ],
        ),
    ]
