# Generated by Django 5.2.1 on 2025-06-03 13:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0002_candidate_caste_candidate_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationQualification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=100)),
                ('specialisation', models.CharField(max_length=100)),
                ('board_institute', models.CharField(max_length=100)),
                ('month_of_completion', models.CharField(max_length=20)),
                ('year_of_completion', models.CharField(max_length=4)),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_obtained', models.CharField(choices=[('First', 'First'), ('Second', 'Second'), ('Third', 'Third')], max_length=10)),
                ('certificate', models.FileField(blank=True, null=True, upload_to='certificates/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='education_qualifications', to='candidates.candidate')),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('from_date', models.DateField()),
                ('to_date', models.DateField()),
                ('tasks_duties', models.TextField()),
                ('certificate', models.FileField(blank=True, null=True, upload_to='experience_certificates/')),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_experiences', to='candidates.candidate')),
            ],
        ),
    ]
