# Generated by Django 5.2.1 on 2025-06-04 07:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0003_educationqualification_workexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='experience_match',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='photos/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to='signatures/'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
