# Generated by Django 5.2.1 on 2025-06-04 08:04

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0004_candidate_created_at_candidate_experience_match_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.models.photo_upload_path),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='signature',
            field=models.ImageField(blank=True, null=True, upload_to=candidates.models.signature_upload_path),
        ),
        migrations.AlterField(
            model_name='educationqualification',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.certificate_upload_path),
        ),
        migrations.AlterField(
            model_name='workexperience',
            name='certificate',
            field=models.FileField(blank=True, null=True, upload_to=candidates.models.exp_certificate_upload_path),
        ),
    ]
